### PR TITLE
fix roughly

### LINKED ISSUE #27: Update UI of wallet

### PR DESCRIPTION
**Pull request by ys1111**
Closes #27

### CODE REVIEW

**Comment by syuhei176** [comment]
please resolve conflicts ;;)

File: app/app.js [hunk 1]
```diff
@@ -90,93 +115,145 @@ class App extends Component {
...
+                            </Table.Cell>
+                          </Table.Row>
+                        );
+                      }) 
+                    : null
+                }
+              </Table.Body>
+            </Table>
+
+            {/* <Divider />
```
Comment (syuhei176) [inline app/app.js]: @ys1111 can you check? please merge master first.

**Comment by syuhei176** [comment]
merge, will fix in other PRs )b
